services:
  postgres:
    image: postgres:16
    container_name: postgres_ovb
    environment:
      POSTGRES_USER: ovb
      POSTGRES_PASSWORD: ovb
      POSTGRES_DB: ovb
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: